# config/app.yml for rails-settings-cached
defaults: &defaults
  max_assignments: 5
  site_title: "Russian Platform"
  footer_message: "<p>Для справок <a href='mailto:brandeisapprenticeship@gmail.com'>brandeisapprenticeship@gmail.com</a></p>"

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
