# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6199472c2eb6e4fc3f2a7432ccb81fbd9aa8f3cc98eae6e0c16416acf297ddc26ae4c4cd9bcdab7b10facbf2ed502bddb8d13cd9797af5fc3bf8433b86e31e33

test:
  secret_key_base: 6ef384b90f1bdcf572fcbf05ea0dccacfe07436322a613a3447702c68fc5a023949b9e39ec6a0a835299f079a8262bfbe4ddb3a33765c7181a7b87d6a9cfbaa4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
